- name: Configure backend server
  hosts: backend
  become: yes
  vars:
  tasks:
  - name: Disabling Nodejs 18 version
    ansible.builtin.command: dnf module disable nodejs -y
    
  - name: Enable Nodejs 20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: installed

  - name: Adding expense user
    ansible.builtin.user:
      name:  expense