- name: Configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.daws304.online
  tasks:
  - name: Install MySQL Server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: Start and Enable Server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9
      


  - name: Check DB Connect
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output
